"""added articles

Revision ID: c7f0f8006cfc
Revises: f9b2763bf8c1
Create Date: 2023-05-02 16:45:31.345667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f0f8006cfc'
down_revision = 'f9b2763bf8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=63), nullable=False),
    sa.Column('body', sa.String(length=2047), nullable=False),
    sa.Column('attachments', sa.String(length=10000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_attachments'), ['attachments'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_body'), ['body'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', sa.Integer(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1023),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_comment_article'), ['article'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_article'))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1023),
               nullable=True)
        batch_op.drop_column('article')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_rating'))
        batch_op.drop_index(batch_op.f('ix_article_body'))
        batch_op.drop_index(batch_op.f('ix_article_attachments'))

    op.drop_table('article')
    # ### end Alembic commands ###
