"""Initial migration.

Revision ID: f9b2763bf8c1
Revises: 
Create Date: 2023-05-01 20:15:42.255924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b2763bf8c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=127), nullable=True),
    sa.Column('body', sa.String(length=1023), nullable=True),
    sa.Column('response', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_body'), ['body'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_item'), ['item'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_response'), ['response'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_username'), ['username'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=127), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.drop_index(batch_op.f('ix_item_description'))
        batch_op.drop_index(batch_op.f('ix_item_cost'))

    op.drop_table('item')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_username'))
        batch_op.drop_index(batch_op.f('ix_comment_response'))
        batch_op.drop_index(batch_op.f('ix_comment_item'))
        batch_op.drop_index(batch_op.f('ix_comment_body'))

    op.drop_table('comment')
    # ### end Alembic commands ###
